# Generated by Django 5.0.4 on 2024-05-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('cooking_time_hours', models.IntegerField(blank=True, null=True)),
                ('cooking_time_minutes', models.IntegerField(blank=True, null=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('course_of_meal', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
